### ISSUE TITLE
Items to be Whitelisted by Lag'B'Gone

### ISSUE THREAD

**Issue by SayYesToGiygas** [SalmonSays/SlamminSalmonsMinesRecrafted#10]
Paintings, Item Frames, Boats

**Comment by SayYesToGiygas** [comment]
Fairy Lights

**Comment by SalmonSays** [comment]
Items have been set to blacklist mode, so Lag B Gone will police animal breeding and unload chunks (if necessary) automagically without touching stuff like paintings, frames, boats, and fairy lights
