### ISSUE TITLE
Chat Censor Mod [ preferrably one that harms ;) ]

### ISSUE THREAD

**Issue by SayYesToGiygas** [SalmonSays/SlamminSalmonsMinesRecrafted#7]

**Comment by SayYesToGiygas** [comment]
I've already got a naughty word blacklist at the ready for when we go public.

**Comment by SalmonSays** [comment]
Added Watch Yo Profanity to the next immediate pack update

**Comment by SalmonSays** [comment]
Forge Essentials has this baked in now.
